### ISSUE TITLE
Invesitgate performing one big commit after all works/orphans

### ISSUE THREAD

**Issue by cdrini** [cdrini/openlibrary#8]
We currently perform a solr commit every 5000 works/orphans; but commits are expensive. Investigate if we can do it less frequently.

**Comment by tfmorris** [comment]
Doesn't the current import defer all commits until the end?

**Comment by cdrini** [comment]
Oh, yes, I added that here: https://github.com/internetarchive/openlibrary/pull/1843/commits/fcb41c07111d477936dd017ca10d01295bb60538

It had virtually not effect on runtime tbh :P I did it mostly for consistency with how authors is doing things.
